DEBUG:root:Popping some data (checksum): bytearray(b'5')
DEBUG:root:Popping some data (SYNC): bytearray(b'\n')
DEBUG:root:Popping some data (SYNC): bytearray(b'$')
DEBUG:root:Popping some data (SYNC): bytearray(b'`')
DEBUG:root:Popping some data (SYNC): bytearray(b'\x16')
DEBUG:root:Popping some data (SYNC): bytearray(b'\x00')
DEBUG:root:Popping some data (SYNC): bytearray(b'\x0e')
DEBUG:root:Popping some data (SYNC): bytearray(b'\x00')
DEBUG:root:Popping some data (SYNC): bytearray(b'l')
DEBUG:root:Popping some data (SYNC): bytearray(b'l')
DEBUG:root:Popping some data (SYNC): bytearray(b'i')
DEBUG:root:Popping some data (SYNC): bytearray(b's')
DEBUG:root:Popping some data (SYNC): bytearray(b' ')
DEBUG:root:Popping some data (SYNC): bytearray(b'm')
DEBUG:root:Popping some data (SYNC): bytearray(b'a')
DEBUG:root:Popping some data (SYNC): bytearray(b'x')
DEBUG:root:Popping some data (SYNC): bytearray(b'i')
DEBUG:root:Popping some data (SYNC): bytearray(b'm')
DEBUG:root:Popping some data (SYNC): bytearray(b'u')
DEBUG:root:Popping some data (SYNC): bytearray(b's')
DEBUG:root:Popping some data (SYNC): bytearray(b' ')
DEBUG:root:Popping some data (SYNC): bytearray(b'a')
DEBUG:root:Popping some data (SYNC): bytearray(b'u')
DEBUG:root:Popping some data (SYNC): bytearray(b'g')
DEBUG:root:Popping some data (SYNC): bytearray(b'u')
DEBUG:root:Popping some data (SYNC): bytearray(b'e')
DEBUG:root:Popping some data (SYNC): bytearray(b',')
DEBUG:root:Popping some data (SYNC): bytearray(b' ')
DEBUG:root:Popping some data (SYNC): bytearray(b'v')
DEBUG:root:Popping some data (SYNC): bytearray(b'e')
DEBUG:root:Popping some data (SYNC): bytearray(b'l')
DEBUG:root:Popping some data (SYNC): bytearray(b' ')
DEBUG:root:Popping some data (SYNC): bytearray(b'l')
DEBUG:root:Popping some data (SYNC): bytearray(b'a')
DEBUG:root:Popping some data (SYNC): bytearray(b'c')
DEBUG:root:Popping some data (SYNC): bytearray(b'i')
DEBUG:root:Popping some data (SYNC): bytearray(b'n')
DEBUG:root:Popping some data (SYNC): bytearray(b'i')
DEBUG:root:Popping some data (SYNC): bytearray(b'a')
DEBUG:root:Popping some data (SYNC): bytearray(b' ')
DEBUG:root:Popping some data (SYNC): bytearray(b'f')
DEBUG:root:Popping some data (SYNC): bytearray(b'e')
DEBUG:root:Popping some data (SYNC): bytearray(b'l')
DEBUG:root:Popping some data (SYNC): bytearray(b'i')
DEBUG:root:Popping some data (SYNC): bytearray(b's')
DEBUG:root:Popping some data (SYNC): bytearray(b' ')
DEBUG:root:Popping some data (SYNC): bytearray(b'm')
DEBUG:root:Popping some data (SYNC): bytearray(b'o')
DEBUG:root:Popping some data (SYNC): bytearray(b'l')
DEBUG:root:Popping some data (SYNC): bytearray(b'l')
DEBUG:root:Popping some data (SYNC): bytearray(b'i')
DEBUG:root:Popping some data (SYNC): bytearray(b's')
DEBUG:root:Popping some data (SYNC): bytearray(b' ')
DEBUG:root:Popping some data (SYNC): bytearray(b'q')
DEBUG:root:Popping some data (SYNC): bytearray(b'u')
DEBUG:root:Popping some data (SYNC): bytearray(b'i')
DEBUG:root:Popping some data (SYNC): bytearray(b's')
DEBUG:root:Popping some data (SYNC): bytearray(b'.')
DEBUG:root:Popping some data (SYNC): bytearray(b' ')
DEBUG:root:Popping some data (SYNC): bytearray(b'V')
DEBUG:root:Popping some data (SYNC): bytearray(b'e')
DEBUG:root:Popping some data (SYNC): bytearray(b's')
DEBUG:root:Popping some data (SYNC): bytearray(b't')
DEBUG:root:Popping some data (SYNC): bytearray(b'i')
DEBUG:root:Popping some data (SYNC): bytearray(b'b')
DEBUG:root:Popping some data (SYNC): bytearray(b'u')
DEBUG:root:Popping some data (SYNC): bytearray(b'l')
DEBUG:root:Popping some data (SYNC): bytearray(b'u')
DEBUG:root:Popping some data (SYNC): bytearray(b'm')
DEBUG:root:Popping some data (SYNC): bytearray(b' ')
DEBUG:root:Popping some data (SYNC): bytearray(b'i')
DEBUG:root:Popping some data (SYNC): bytearray(b'a')
DEBUG:root:Popping some data (SYNC): bytearray(b'c')
DEBUG:root:Popping some data (SYNC): bytearray(b'u')
DEBUG:root:Popping some data (SYNC): bytearray(b'l')
DEBUG:root:Popping some data (SYNC): bytearray(b'i')
DEBUG:root:Popping some data (SYNC): bytearray(b's')
DEBUG:root:Popping some data (SYNC): bytearray(b' ')
DEBUG:root:Popping some data (SYNC): bytearray(b'p')
DEBUG:root:Popping some data (SYNC): bytearray(b'l')
DEBUG:root:Popping some data (SYNC): bytearray(b'a')
DEBUG:root:Popping some data (SYNC): bytearray(b'c')
DEBUG:root:Popping some data (SYNC): bytearray(b'e')
DEBUG:root:Popping some data (SYNC): bytearray(b'r')
DEBUG:root:Popping some data (SYNC): bytearray(b'a')
DEBUG:root:Popping some data (SYNC): bytearray(b't')
DEBUG:root:Popping some data (SYNC): bytearray(b' ')
DEBUG:root:Popping some data (SYNC): bytearray(b'f')
DEBUG:root:Popping some data (SYNC): bytearray(b'a')
DEBUG:root:Popping some data (SYNC): bytearray(b'u')
DEBUG:root:Popping some data (SYNC): bytearray(b'c')
DEBUG:root:Popping some data (SYNC): bytearray(b'i')
DEBUG:root:Popping some data (SYNC): bytearray(b'b')
DEBUG:root:Popping some data (SYNC): bytearray(b'u')
DEBUG:root:Popping some data (SYNC): bytearray(b'\x84')
DEBUG:root:Popping some data (SYNC): bytearray(b'S')

bytearray(b'\xf2O$`\x16\x00\x0e\x00llis maximus augue, vel lacinia felis mollis quis. Vestibulum iaculis placerat faucibuVZ')